name: demo_fastapi_app

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__NAME:-fastapi_db}
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - dbnet
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${APP_CONFIG__PGADMIN__EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${APP_CONFIG__PGADMIN__PASSWORD}
    ports:
      - "127.0.0.1:5050:80" # Внутри pgAdmin слушает порт 80
    networks:
      - dbnet
    depends_on:
      - db
    restart: unless-stopped

networks:
  dbnet:
    driver: bridge

volumes:
  pg_data: