#!/usr/bin/env bash
#
# Generates the production secrets file — every configuration value the stack
# needs that a deploy must never rewrite. Run once, on the server:
#
#     bash gen-secrets.sh [/opt/alerts/.env.secrets]
#
# Write-once by design. There is no --force and no prompt to overwrite:
# regenerating would rotate the database and Grafana passwords, which are
# seed-only (see the header it writes), leaving the containers holding
# credentials their data directories never heard of. Deleting the file first is
# the deliberate act that allows a second run.

set -euo pipefail

TARGET="${1:-/opt/alerts/.env.secrets}"

die() { printf 'gen-secrets: %s\n' "$1" >&2; exit 1; }

# Order matters: the existence check comes before the prompts, so a second run
# fails instantly instead of asking for three values it will then throw away.
[[ -e "$TARGET" ]] && die "$TARGET exists — delete it deliberately to regenerate"
[[ -d "$(dirname "$TARGET")" ]] || die "$(dirname "$TARGET") does not exist"
[[ -t 0 ]] || die "needs a terminal: three values have to be typed in"

# Hex, and that is a requirement rather than a taste. Both env files are passed
# to `docker compose --env-file`, and compose interpolates ${...} inside their
# values — a generator over printable ASCII would eventually emit a $ and the
# value would silently become something else. od avoids the classic
# `tr -dc < /dev/urandom | head` pipeline, which dies of SIGPIPE under pipefail.
rand_hex() { od -vAn -N"$1" -tx1 /dev/urandom | tr -d ' \n'; }

# check NAME VALUE — a pasted value must be non-empty and free of dollar signs,
# for the same interpolation reason.
check() {
  [[ -n "$2" ]] || die "$1 must not be empty"
  case "$2" in
    *'$'*) die "$1 contains a \$, which compose would interpolate away" ;;
  esac
}

printf 'Writing %s\n\n' "$TARGET"
printf 'Three values cannot be generated. Have them ready:\n'
printf '  - a mailbox for Let'"'"'s Encrypt expiry notices\n'
printf '  - the Resend API key (re_...), from your password manager\n'
printf '  - the Telegram bot token\n\n'

read -r -p 'ACME contact e-mail: ' acme_email
check ACME_EMAIL "$acme_email"

read -rs -p 'Resend API key: ' smtp_password; printf '\n'
check APP_CONFIG__SMTP__PASSWORD "$smtp_password"

read -rs -p 'Telegram bot token: ' bot_token; printf '\n'
check APP_CONFIG__TELEGRAM__BOT_TOKEN "$bot_token"

# 077 before the file exists: chmod afterwards would leave a window in which
# the secrets are world-readable.
umask 077

cat > "$TARGET" <<EOF
# Generated by deploy/gen-secrets.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC').
# Mode 600. A deploy never rewrites this file — .env is the one deploys own.
#
# The database and Grafana passwords are SEED-ONLY. Postgres reads its password
# when the data directory is first initialised, Grafana when its database is
# created. Editing them here afterwards changes nothing but what the containers
# believe: the services keep the password they were born with. Rotating them
# for real means changing them inside the running service (ALTER ROLE,
# grafana-cli admin reset-admin-password) and here, in the same sitting.

APP_CONFIG__DB__NAME=crypto_alerts_db
APP_CONFIG__DB__USERNAME=alerts
APP_CONFIG__DB__PASSWORD=$(rand_hex 24)
APP_CONFIG__DB__PORT=5432

APP_CONFIG__RABBITMQ__USERNAME=alerts
APP_CONFIG__RABBITMQ__PASSWORD=$(rand_hex 24)

APP_CONFIG__AUTH__SECRET_KEY=$(rand_hex 32)

# Resend: the username is the literal "resend", set in deploy/compose.prod.yaml
APP_CONFIG__SMTP__PASSWORD=$smtp_password

APP_CONFIG__TELEGRAM__BOT_TOKEN=$bot_token

GRAFANA_PASSWORD=$(rand_hex 18)

# Let's Encrypt sends certificate-expiry notices here. Required: the overlay
# reads it as \${ACME_EMAIL:?}, so an empty value fails the whole render.
ACME_EMAIL=$acme_email
EOF

chmod 600 "$TARGET"

printf '\n'
stat -c 'wrote %n  mode %a  owner %U:%G' "$TARGET"
printf '\n%s variables, %s of them generated here and existing nowhere else.\n' \
  "$(grep -c '^[A-Z]' "$TARGET")" 4
printf 'Back it up only with the rest of the server: it is not reproducible.\n'
